### ISSUE TITLE
[Feat] 권한설정과 설정화면 로직 구현

### ISSUE THREAD

**Issue by Monfi98** [DeveloperAcademy-POSTECH/2024-NC2-A50-ScreenTime#13]
## Issue

권한 설정 및 설정화면에 관한 로직들을 구현합니다.

## Tasks

- [x] 알림 및 스크린타임 권한 설정
- [x] 스포일 앱 선택 로직
- [x] 제한 시간 설정 로직
- [x] 알림 설정 로직
- [x] 총 설정화면에서 표시
